- type: log
  paths:
    - /opt/logs/geoserver-logs/*slave*.log*
  scan_frequency: 10s
  tags: ["geoserver", "slave", "logs", "log"]
  fields_under_root: true
  fields:
    type: geoserver-logs
  multiline.pattern: '^([0-9]{4}-[0-9]{2}-[0-9]{2})'
  multiline.negate: true
  multiline.match: after