filebeat.inputs:
- type: log
  id: geoserver-filestream
  paths:
    - C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\geoserver\data\logs\*.log
  tags: ["geoserver", "logs", "log", "env1"]
  fields:
    app_context: geoserver_logs
    type: geoserver-logs
  fields_under_root: true
  multiline.pattern: '^([0-9]{4}-[0-9]{2}-[0-9]{2})'
  multiline.negate: true
  multiline.match: after

- type: log
  id: audit-filestream
  paths:
    - C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\geoserver\data\audit\*.log
  tags: ["geoserver", "audit", "env1"]
  fields:
    app_context: geoserver_audit_logs
    type: geoserver-audit
  fields_under_root: true

output.logstash:
  hosts: ["192.168.122.1:9601"]
  index: filebeat-env1
  
