# set logging to info in prod
logging.level: debug

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.config.inputs:
  enabled: true
  path: ${path.config}/conf.d/*.yml

output.logstash:
  hosts: ["elkstack1.int.unavco.org:5044"]
