filebeat:
 inputs:
   - type: log
     id: geoserver-filestream
     paths:
       - /var/geoserver/audits/*.log
     tags: ["geoserver", "master"]
     fields:
       type: geoserver-audit
     fields_under_root: true
     input_type: log

output.logstash:
  hosts: ["logstash01:9601"]
