filebeat.inputs:
- type: log
  id: geoserver-filestream
  paths:
    - /var/geoserver/logs/*.log
  tags: ["geoserver", "logs", "log", "dev"]
  fields:
    app_context: geoserver_logs
    type: geoserver-logs
  fields_under_root: true
  multiline.pattern: '^([0-9]{4}-[0-9]{2}-[0-9]{2})'
  multiline.negate: true
  multiline.match: after


- type: log
  id: audit-filestream
  paths:
    - /var/geoserver/audits/*.log
  tags: ["geoserver", "audit", "dev"]
  fields:
    app_context: geoserver_audit_logs
    type: geoserver-audit
  fields_under_root: true 

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: ~

#setup.kibana:
#  host: ${KIBANA_HOSTS}
#  username: ${ELASTIC_USER}
#  password: ${ELASTIC_PASSWORD} 

output.logstash:
  hosts: ["logstash:9601"]


#output.elasticsearch:
#  hosts: ${ELASTIC_HOSTS}
#  username: ${ELASTIC_USER}
#  password: ${ELASTIC_PASSWORD}
#  ssl.enabled: true
#  ssl.certificate_authorities: "certs/ca/ca.crt"
  
